steps:
  - command: ".buildkite/build.sh"
    artifact_paths: "dist/*"
    plugins:
    - docker-login#v2.1.0:
        username: endqwerty
        password-env: MY_DOCKER_LOGIN_PASSWORD
    - docker#v5.3.0:
        image: "node:18-alpine"
        env:
          - BUILDKITE_BUILD_NUMBER
          - BUILDKITE_PULL_REQUEST
    - gencer/cache#v2.4.12:
        id: node # or node-16
        backend: rsync # Optional. Default `backend` is already set to `tarball`
        key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum './package-lock.json' }}" # Calculate whole 'app/javascript' recursively
        restore-keys:
          - 'v1-cache-{{ id }}-{{ runner.os }}-'
          - 'v1-cache-{{ id }}-'
        rsync:
          path: '/tmp/buildkite-cache' # Defaults to /tmp with v2.4.10+
        paths:
          - node_modules
  - wait
  - commands:
    - "./.buildkite/deploy.sh $build.branch"
    plugins:
    - docker-login#v2.1.0:
        username: endqwerty
        password-env: MY_DOCKER_LOGIN_PASSWORD
    - docker#v5.3.0:
        image: "node:18-alpine"
        env:
          - BUILDKITE_BUILD_NUMBER
          - BUILDKITE_PULL_REQUEST
    - gencer/cache#v2.4.10:
        id: node # or node-16
        backend: rsync # Optional. Default `backend` is already set to `tarball`
        key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum './package-lock.json' }}" # Calculate whole 'app/javascript' recursively
        restore-keys:
          - 'v1-cache-{{ id }}-{{ runner.os }}-'
          - 'v1-cache-{{ id }}-'
        rsync:
          path: '/tmp/buildkite-cache' # Defaults to /tmp with v2.4.10+
        paths:
          - node_modules