steps:
  - command: "./build.sh"
    artifact_paths: "dist/*"
    plugins:
    - docker-login#v2.1.0:
        username: endqwerty
        password-env: MY_DOCKER_LOGIN_PASSWORD
    - docker-compose#v4.7.0:
          config:
            - .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_PULL_REQUEST
          run: build-env
    - gencer/cache#v2.4.12:
        id: node # or node-16
        backend: rsync # Optional. Default `backend` is already set to `tarball`
        key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum './package-lock.json' }}" # Calculate whole 'app/javascript' recursively
        restore-keys:
          - 'v1-cache-{{ id }}-{{ runner.os }}-'
          - 'v1-cache-{{ id }}-'
        rsync:
          path: '/tmp/buildkite-cache' # Defaults to /tmp with v2.4.10+
        paths:
          - node_modules
  - wait
  - commands:
    - "npm i -g vercel"
    - "npx vercel login --token $VERCEL_AUTH"
    - "npm run deploy"
    if: build.branch == "main"
    plugins:
    - docker-login#v2.1.0:
        username: endqwerty
        password-env: MY_DOCKER_LOGIN_PASSWORD
    - docker-compose#v4.7.0:
          config:
            - .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_PULL_REQUEST
            - VERCEL_AUTH
          run: build-env
    - gencer/cache#v2.4.10:
        id: node # or node-16
        backend: rsync # Optional. Default `backend` is already set to `tarball`
        key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum './package-lock.json' }}" # Calculate whole 'app/javascript' recursively
        restore-keys:
          - 'v1-cache-{{ id }}-{{ runner.os }}-'
          - 'v1-cache-{{ id }}-'
        rsync:
          path: '/tmp/buildkite-cache' # Defaults to /tmp with v2.4.10+
        paths:
          - node_modules
  - commands:
    - "npm i -g vercel"
    - "npx vercel login --token $VERCEL_AUTH"
    - "npm run deploy-development"
    if: build.branch == "dev"
    plugins:
    - docker-login#v2.1.0:
        username: endqwerty
        password-env: MY_DOCKER_LOGIN_PASSWORD
    - docker-compose#v4.7.0:
          config:
            - .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_PULL_REQUEST
            - VERCEL_AUTH
          run: build-env
    - gencer/cache#v2.4.10:
        id: node # or node-16
        backend: rsync # Optional. Default `backend` is already set to `tarball`
        key: "v1-cache-{{ id }}-{{ runner.os }}-{{ checksum './package-lock.json' }}" # Calculate whole 'app/javascript' recursively
        restore-keys:
          - 'v1-cache-{{ id }}-{{ runner.os }}-'
          - 'v1-cache-{{ id }}-'
        rsync:
          path: '/tmp/buildkite-cache' # Defaults to /tmp with v2.4.10+
        paths:
          - node_modules