name: Publish Website

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Checkout project
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build
        run: |
          npm ci
          npm run build-production

      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./dist
          files: |
            ./index.html
            ./components/*
          outPath: github-pages.tar.gz

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.5

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
